apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend
    spec:
      containers:
      - name: toybackend
        image: toybackend:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
          - containerPort: 8080
