apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend
    spec:
      containers:
      - name: toybackend
        image: toybackend:latest
        env:
          - name: DB_USERNAME
            value: root
          - name: DB_URL
            value: mysql
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: toybox
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mysql-pass
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
          - containerPort: 8080
