---
# service to expose the backend to the world
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31111
# ---
# # service to allow pods access to the backend
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend
# spec:
#   selector:
#     app: backend
#   ports:
#   - port: 8080
#     targetPort: 8080
#     protocol: TCP
---
# service to expose the frontend to the world
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30033
  selector:
    app: frontend