apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reporting-cron-job
# cron job spec
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    # job spec
    spec:
      completions: 3
      parallelism: 3
      template:
        # pod spec
        spec:
          containers:
            - name: math-add
              image: ubuntu
              command: ['expr', '3', '+', '2']
          restartPolicy: Never
  