apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    # ReadOnlyMany, ReadWriteOnce, or ReadWriteMany
    - ReadWriteOnce
  capacity:
    storage: "1Gi"
  # hostPath -- not for use in production
  # in production, replace with aws elastic block store or similar
  hostPath:
    path: /tmp/data
  # Retain, Recycle, or Delete
  persistentVolumeReclaimPolicy: Retain